// Code generated by Slice Machine. DO NOT EDIT.

import External from './External';
import Image from './Image';
import InstagramPost from './InstagramPost';
import Text from './Text';
import TextImage from './TextImage';

export {
	External,
	Image,
	InstagramPost,
	Text,
	TextImage,
};

export const components = {
	external: External,
	image: Image,
	instagram_post: InstagramPost,
	text: Text,
	text_image: TextImage,
};
