// Code generated by Slice Machine. DO NOT EDIT.

import External from './External';
import Image from './Image';
import Text from './Text';

export {
	External,
	Image,
	Text,
};

export const components = {
	external: External,
	image: Image,
	text: Text,
};
